spring:
  application:
    name: yuapi-interface
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8123
  servlet:
    context-path: /api

yuapi:
  client:
    access-key: yupi
    secret-key: abcdefgh